### PR TITLE
3715 - 0

### PR DESCRIPTION
**Pull request by Almix047**
## Номер
3715

## Номер задания
0

## Ссылка на видео с демо
https://youtu.be/-mXL8xZBv4E

## Комментарии
Done :+1:

### CODE REVIEW

**Comment by tester047** [comment]
> please, rename commits according to: https://chris.beams.io/posts/git-commit/

I hope, it's done.

**Comment by Almix047** [comment]
> please, rename commits according to: https://chris.beams.io/posts/git-commit/

I hope, it,s done

**Comment by anatoliliotych** [comment]
Please no future time in commit messages...

**Comment by Almix047** [comment]
> no future time in commit messages

ОК

**Comment by Almix047** [comment]
> check comment

I removed the future time in commit messages.

**Pull request merged**
